#!/usr/bin/env bash
# script that pings a host 5x
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit
elif [ $# -gt 1]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit
else
    ping "$1" -c 5
fi