#!/usr/bin/env bash
# This script checks if a host on the network is reachable by pinging it with 5 ICMP echo requests.
# If no IP address is provided as an argument, it displays a usage message.

if [ "$1" == "" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi