#!/usr/bin/env bash
# Check if the file does not exist, create it

file="/var/run/myscript.pid"

if [ ! -e "$file" ]; then
  touch "$file"
fi

# Run sleep command in the background and store its process ID

sleep 2 &

# Write the process ID of the last background command to the file

echo "$!" > "$file"

trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

trap "echo Y U no love me?!" SIGINT

while true; do
  echo "To infinity and beyond"
  sleep 2
done
