#!/usr/bin/env bash
# Script saying "Best School" and "HI"

counter=1
while [ $counter -lt 10 ]
do
        echo "Best School"
        if [[ "$counter" -eq 9 ]]
        then
                echo "HI"
        fi
        ((counter++))
done
