#!/usr/bin/env bash
# Script saying "Best School" and "HI"

counter=1

while [ $counter -lt 10 ]
do
        if [ "$counter" -eq 9 ]
        then
                echo "Hi"
        fi
        echo "Best School"
        (( counter++ ))
done
