#!/usr/bin/env bash
# displays Holberton School 10 times.
counter=1
while [ $counter -lt 21 ]
do
	echo "$counter"
	case "$counter" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	let counter++
done
