#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i -e 's/^127\.0\.0\.1/127.0.0.2/' -e 's/^.*facebook\.com/8.8.8.8 facebook.com/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
